### PR TITLE
Issue 4/compare installed version

### LINKED ISSUE #4: Cookbook fails to upgrade firefox after downloading a new version
The guard in the 'untar-firefox' resource is flawed. It will only explode a given firefox version when there is not an existing installation of firefox.

https://github.com/rapid7-cookbooks/firefox_package/blob/master/libraries/firefox_package.rb#L89

The expected behavior is for the cookbook to download and explode the new version idempotently. Additionally, it should clean up the old cache file to prevent eventually filling the disk.

### PR DESCRIPTION
**Pull request by rhass**
# Summary

This closes #4 by adding the capability to check the installed version, if one exists, to see if a new version should be exploded.
# Validation
- [x] The Audit Mode tests should succeed in the pull request build on travis.

### CODE REVIEW

File: libraries/firefox_package.rb [hunk 1]
```diff
@@ -92,28 +91,69 @@ def explode_tarball(filename, dest_path)
 
       execute 'untar-firefox' do
         command "tar --strip-components=1 -xjf #{filename} -C #{dest_path}"
-        not_if { ::File.exist?(::File.join(dest_path, 'firefox')) }
+        not_if {
+          installed_version(
+            ::File.join(dest_path, 'firefox')
+          ) > parse_version(filename)
```
Comment (erran-r7) [inline libraries/firefox_package.rb]: What if the versions are equal?

File: libraries/firefox_package.rb [hunk 2]
```diff
@@ -92,28 +91,69 @@ def explode_tarball(filename, dest_path)
...
+    # can be used for comparing versions like 38.0 and 38.0.0.
+    def parse_version(str)
+      chef_gem 'versionomy' do
+        compile_time true
+      end
+
+      require 'versionomy'
+
+      version_string = /.\d\.\d.\d|\d+.\d/.match(str).to_s
+      Versionomy.parse(version_string)
```
Comment (erran-r7) [inline libraries/firefox_package.rb]: Could we just use Ruby's built in `Gem::Version.new` instead of parsing via the _new_ Versionomy dependency here?

File: libraries/firefox_package.rb [hunk 3]
```diff
@@ -92,28 +91,69 @@ def explode_tarball(filename, dest_path)
...
+    # @return [String] When version is an ESR, the value is returned with the
+    # string EST appended.
     def windows_long_version(version)
       if version.nil?
         version = parse_version(filename)
-        long_version = "#{version}"
+        long_version = version.to_s
         if esr?(filename)
-          long_version = "#{parse_version(filename)} ESR"
+          long_version = "#{parse_version(filename).to_s} ESR"
```
Comment (erran-r7) [inline libraries/firefox_package.rb:146]: No reason to call `String#to_s` as it is automatically called when you use the interpolation syntax.

File: test/cookbooks/firefox_package_test/recipes/default.rb [hunk 4]
```diff
@@ -11,5 +11,18 @@
   end
 end
 
+# Copy an old version into a new version named directory to test
+# upgrading without having to worry about the paths.
+# There has to be a better way to copy directories... but it is not obvious.
+unless platform?('windows')
```
Comment (erran-r7) [inline test/cookbooks/firefox_package_test/recipes/default.rb:17]: Should we be using `not_if` guards based on `platform?('windows')` instead of this conditional block (as per [FC023](http://acrmp.github.io/foodcritic/#FC023))?

Comment (rhass-r7) [inline test/cookbooks/firefox_package_test/recipes/default.rb:17]: FC023 deal specifically with string interpolation. We are using the PlatformIntrospection class here. Good eye though.

File: libraries/firefox_package.rb (hunk 3 above)
Comment (rhass-r7) [inline libraries/firefox_package.rb:146]: I think this was an issue with Versionomy, but I since switched to`Gem::Version` as I didn't realize that `Gem::Version` would do what I wanted at time.

Comment (rhass-r7) [inline libraries/firefox_package.rb]: No, this is still an issue. We need to convert to string:

             TypeError
             ---------
             no implicit conversion of Fixnum into String

**Comment by erran-r7** [comment]
@rhass-r7 You've got my :shipit:.
